development:
  adapter: postgresql
  encoding: unicode
  database: telegram_data_new
  pool: 5
  timeout: 5000
  username: pguser
  password: 123

test:
  adapter: postgresql
  encoding: unicode
  database: telegram_data_test_new
  pool: 5
  timeout: 5000
  username: pguser
  password: 123
